### ISSUE TITLE
What is the name of the text font used in the editor when taking the screenshots ?

### ISSUE THREAD

**Issue by astrolemonade** [sergeymakinen/jetbrains-github-theme#2]

**Comment by cata0309** [comment]
And also the UI font

**Comment by cata0309** [comment]
Founded

**Comment by astrolemonade** [comment]
SF Mono for the editor

**Comment by astrolemonade** [comment]
What is the UI font?

**Comment by sergeymakinen** [comment]
Should be default one for macOS 10.15:
<img width="540" alt="image" src="https://user-images.githubusercontent.com/983964/77156740-0abaee80-6ab1-11ea-994a-aca730202e63.png">
